Repository DowaDream/DowaDream-Server, pull requests merged in 2023-08, with the labels that each got.

#7 [FIX] 소셜로그인 수정
  config/settings.py
  requirements.txt
  user/jwt_token.py
  user/response.py
  user/service.py
  user/views.py
Labels: fix

#13 [CHORE] CRLF 통일
  .gitattributes
Labels: chore

#14 [Feat] 1365 API 추가
  config/settings.py
  config/urls.py
  search/__init__.py
  search/admin.py
  search/apps.py
  search/migrations/__init__.py
  search/models.py
  search/service.py
  search/tests.py
  search/urls.py
  search/views.py
Labels: feat

#10 [FEAT] 리뷰 CRUD
  config/permissions.py
  config/settings.py
  config/urls.py
  review/__init__.py
  review/admin.py
  review/apps.py
  review/migrations/0001_initial.py
  review/migrations/0002_remove_image_rid_image_review.py
  review/migrations/__init__.py
  review/models.py
  review/response.py
  review/serializers.py
  review/service.py
  review/tests.py
  review/urls.py
  review/views.py
  user/migrations/0001_initial.py
  user/response.py
Labels: feat

#15 [FEAT] CI/CD
  .github/workflows/cicd.yml
Labels: feat

#16 [FEAT] 리뷰 댓글CRUD + 인가
  review/response.py
  review/s3_manager.py
  review/service.py
  review/views.py
Labels: feat, refactor

#20 [FIX] 리뷰 S3 에러 및 Query Param 추가
  review/comment_service.py
  review/image_service.py
  review/migrations/0005_review_actplace_review_is_public_review_region_and_more.py
  review/migrations/0006_alter_review_is_public.py
  review/models.py
  review/response.py
  review/review_service.py
  review/s3_manager.py
  review/urls.py
  review/views.py
Labels: fix

#23 [FEAT] 후기 추가 API
  review/response.py
  review/review_service.py
  review/urls.py
  review/views.py
Labels: feat

#24 [FEAT] 유저 관련 API
  review/response.py
  review/views.py
  user/migrations/0002_remove_user_age_remove_user_category_and_more.py
  user/migrations/0003_alter_user_resol_msg.py
  user/models.py
  user/response.py
  user/service.py
  user/urls.py
  user/views.py
Labels: feat

#28 [FEAT] 봉사 스크랩/응원/내가 한 봉사
  config/settings.py
  config/urls.py
  program/__init__.py
  program/admin.py
  program/apps.py
  program/migrations/0001_initial.py
  program/migrations/0002_rename_reviewed_program_interaction_clipped.py
  program/migrations/__init__.py
  program/models.py
  program/response.py
  program/serializers.py
  program/service.py
  program/tests.py
  program/urls.py
  program/views.py
  review/admin.py
  review/migrations/0007_cheered_review.py
  review/models.py
  review/response.py
  review/review_service.py
  review/serializers.py
  review/urls.py
  review/views.py
  user/views.py
Labels: feat

#31 [CHORE] Swagger annotation
  config/settings.py
  program/models.py
  program/serializers.py
  program/views.py
  review/migrations/0008_rename_category_review_tag_remove_review_actplace_and_more.py
  review/models.py
  review/serializers.py
  review/urls.py
  review/views.py
  search/views.py
  user/migrations/0004_alter_user_fighting_alter_user_profile_img_and_more.py
  user/models.py
  user/serializers.py
  user/views.py
Labels: chore

#32 [FEAT] 유저 관심태그/지역 설정
  program/migrations/0003_alter_program_interaction_cheered_and_more.py
  review/migrations/0009_remove_review_region_remove_review_tag.py
  review/models.py
  review/review_service.py
  review/serializers.py
  review/views.py
  user/migrations/0001_initial.py
  user/migrations/0002_remove_user_age_remove_user_category_and_more.py
  user/migrations/0003_alter_user_resol_msg.py
  user/migrations/0004_alter_user_fighting_alter_user_profile_img_and_more.py
  user/models.py
  user/response.py
  user/serializers.py
  user/service.py
  user/urls.py
  user/views.py
Labels: feat

#37 [CHORE] search 리팩토링
  config/settings.py
  config/urls.py
  program/response.py
  program/serializers.py
  program/service.py
  program/urls.py
  program/views.py
  search/__init__.py
  search/admin.py
  search/apps.py
  search/migrations/__init__.py
  search/models.py
  search/response.py
  search/serializers.py
  search/service.py
  search/tests.py
  search/urls.py
  search/views.py
Labels: chore

#41 [FIX] 유저/리뷰 관련 수정사항
  review/models.py
  review/review_service.py
  review/serializers.py
  review/views.py
  user/response.py
  user/serializers.py
  user/service.py
  user/urls.py
  user/views.py
Labels: feat

#43 [FEAT] 응원하기순 봉사 추천
  config/settings.py
  program/dto.py
  program/response.py
  program/search_service.py
  program/service.py
  program/urls.py
  program/views.py
  review/views.py
  user/admin.py
  user/jwt_token.py
  user/urls.py
  user/views.py
Labels: feat

#50 [CHORE] search_service 리팩토링
  program/search_service.py
  program/service.py
  program/views.py
Labels: chore

#52 [FEAT] 모집마감순 엔드포인트 추가
  program/search_service.py
Labels: feat

#54 [FIX] 소셜로그인 에러
  config/settings.py
  user/jwt_token.py
  user/service.py
  user/urls.py
  user/views.py
Labels: feat, fix

#55 [FEAT] 맞춤 후기 필터링
  program/search_service.py
  program/service.py
  program/tag_code_to_name.py
  review/migrations/0010_review_tag.py
  review/migrations/0011_review_region.py
  review/models.py
  review/review_service.py
  review/urls.py
  review/views.py
  user/service.py
  user/views.py
Labels: feat

#59 [FEAT] search keyword if one
  program/search_service.py
  program/views.py
Labels: fix

#64 [Fix] 이미지 필드를 넣지 않아도 오류 생기지 않도록
  review/review_service.py
Labels: fix

#62 [FIX] /search/keyword/ 에서 지역과 태그 중 하나만 보낸 경우 대응
  program/search_service.py
  program/views.py
Labels: bug, fix

#66 [FIX] 유저 확인 로직
  user/service.py
  user/views.py
Labels: fix

#65 [FEAT] 게이지
  program/response.py
  program/service.py
  program/urls.py
  program/views.py
Labels: feat

#68 [FIX] search-all-null-fix
  program/views.py
Labels: fix

#71 [Fix] 봉사상세조회에 스크랩수 및 응원수 추가
  program/search_service.py
Labels: fix

#72 Feat: dday 추가
  program/search_service.py
  program/serializers.py
Labels: fix
